version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - prod_network

  web:
    image: ${DOCKERHUB_USERNAME}/book_shop:${IMAGE_VERSION}
    env_file: .env
    ports:
      - "8003:8000"
    depends_on:
      - db
    networks:
      - prod_network

networks:
  prod_network:
    name: prod_network

volumes:
  postgres_data_prod:
    name: postgres_data_prod
