version: '3.8'

services:
  db_test:
    image: postgres:15
    env_file:
      - .env.test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    container_name: bookshop_db_test

  backend_test:
    build: .
    env_file:
      - .env.test
    ports:
      - "8001:8000"
    depends_on:
      - db_test
    container_name: bookshop_backend_test
    command: >
      sh -c "sleep 3 &&
             python manage.py migrate &&
             gunicorn book_shop.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data_test:
