name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy Dev
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/book_shop
            git pull origin dev
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml up -d --build
